# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fQfSpII4NPzmsgMnFmxOJCgcDRWUe-0t
"""

import numpy as np
import matplotlib.pyplot as plt
import mglearn
import tensorflow as tf

from sklearn.datasets import fetch_lfw_people
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input,Dense

np.random.seed(180)
tf.random.set_seed(180)

people=fetch_lfw_people(
    min_faces_per_person=20,
    resize=0.7
)

print(people.data.shape)
print(people.target.shape)
image_shape=people.images[0].shape

fix,axes=plt.subplots(
    2,
    5,
    figsize=(15,8),
    subplot_kw={'xticks':(),'yticks':()}
)

for target,image,ax in zip(
    people.target,
    people.images,
    axes.ravel()):
  ax.imshow(image)
  ax.set_title(
        people.target_names[target]
    )

plt.show()

X_train,X_test,Y_train,Y_test=train_test_split(
    people.data,
    people.target,
    test_size=0.2,
    random_state=20

)

Y_train=Y_train.astype(int)
Y_test=Y_test.astype(int)

batch_size=len(X_train)

print(
    X_train.shape,
    Y_train.shape,
    Y_test.shape
)

print("peple.images.shape:{}".format(people.images.shape))

print("Number of classes:{}".format(len(people.target_names)))

count=np.bincount(people.target)

for i,(count,name) in enumerate(zip(count,people.target_names)):
    print("{0:25} {1:3}".format(name,count),
          end=""
    )

    if(i+1)%3==0:
      print()

mask=np.zeros(
    people.target.shape,
    dtype=bool
)
for target in np.unique(people.target):
  mask[
      np.where(people.target==target)[0][:50]
  ]=True
X_people=people.data[mask]
y_people=people.target[mask]
X_people=X_people/255.0

X_train,X_test,Y_train,Y_test=train_test_split(
    X_people,
    y_people,
    stratify=y_people,
    random_state=0
)


knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(
    X_train,
    Y_train
)
print("Test set score 1-nn:{:.2f}".format(knn.score(X_test,Y_test)))

mglearn.plots.plot_pca_whitening()
plt.show()

pca=PCA(
    n_components=100,
    whiten=True,
    random_state=0
).fit(X_train)

X_train_pca=pca.transform(X_train)
X_test_pca=pca.transform(X_test)

print("X_train_pca.shape:{}".format(X_train_pca.shape))

knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(
    X_train_pca,
    Y_train
)
print("Test set score pca:{:.2f}".format(knn.score(X_test_pca,Y_test)))

print("pca components shape:{}".format(pca.components_.shape))

fix,axes=plt.subplots(
    3,
    5,
    figsize=(15,12),
    subplot_kw={'xticks':(),'yticks':()}
)

for i,(component,ax) in enumerate(zip(pca.components_,axes.ravel())):
  ax.imshow(component.reshape(image_shape),cmap='viridis')
  ax.set_title("{}.component".format((i+1)))

plt.show()

scaler=MinMaxScaler()
X_train_scaled=scaler.fit_transform(X_train_pca)
X_test_scaled=scaler.transform(X_test_pca)

X_test_scaled=scaler.transform(X_test_pca)

model=Sequential([

    Input(
        shape=(100,)
    ),

    Dense(
        300,
        activation='relu'
    ),
    Dense(
        100,
        activation='relu'
    ),
    Dense(
        len(np.unique(Y_train)),
        activation='softmax'
    )
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history=model.fit(
    X_train_scaled,
    Y_train,
    epochs=20,
    batch_size=batch_size,
    validation_data=(X_test_scaled,Y_test)
)

loss,accuracy=model.evaluate(X_test_scaled,Y_test)
print("Test accuracy:{}".format(accuracy))